config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  devise_for :users
   resources :gigs do
     resource :proposals, except: :index
     collection do
       get :search
     end
   end

   root 'gigs#index'
end

app/models/ability.rb
class Ability < ApplicationRecord

  belongs_to :gig , optional: true
  belongs_to :skill , optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :gigs
end

app/models/gig.rb
class Gig < ApplicationRecord
   belongs_to :user , optional: true
   has_many :proposals
   belongs_to :category  , optional: true
   has_many :abilities
   has_many :skills, through: :abilities
   geocoded_by :location
   after_validation :geocode
   
   def self.search(params)
     gigs = Gig.where("name like ? or description like?", "%#{params[:search]}%",  "%#{params[:search]}%") if params[:search].present?
     gigs
   end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :gig , optional: true
  belongs_to :user , optional: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :abilities
  has_many :gigs, through: :abilities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gigs
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]
	 def index
	 	@gigs = Gig.all.order("created_at DESC").page(params[:page]).per(15)
	 	end
    
	 	def new
	 	@gig = Gig.new
	 	end

	 	def create
	 		@gig = Gig.new(gig_params)
			  respond_to do |format|
		      if @gig.save
		        format.html { redirect_to @gig, notice: 'Post was successfully created.' }
		        format.json { render :show, status: :created, location: @gig }
		      else
		        format.html { render :new }
		        format.json { render json: @gig.errors, status: :unprocessable_entity }
		      end
   		 end
	 	end

	 	def show
	 		@gig = Gig.find(params[:id])
      @proposal
	 	end
    def search
      @gigs = Gig.search(params).page(params[:page]).per(25)
    end
 private
 def set_gig
      @gig = Gig.find(params[:id])
    end
 def gig_params
 	params.require(:gig).permit(:name, :description, :budget, :location, :open)

 end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	def index
	end
	def create
		@gig = Gig.find(params[:gig_id])
		@proposal = @gig.proposals.build(proposal_params)
	end

	private
	def proposal_params
		params.require(:proposal).permit(:bid, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/gigs/index.html.erb
<div class="dashboard">
	<div class="jumbotron">
		<div class="overlay">
			<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-2">
					<h1>Do you looking for a Job?</h1>
				<p>In cursus at diam vitae viverra. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi facilisis tellus sit amet dui elementum congue.</p>
				<button class="btn btn-findjob">find job</button>
				</div>
			</div>
		</div>
		</div>
	</div>
</div>

	<div class="container">
			<div class="row">
			<div class="section-title clearfix medium text-center ">
					<h3 class="heading text-center"> Featured Jobs</h3>

							<i class="fa fa-briefcase" aria-hidden="true"></i>

				</div>
				<% if user_signed_in? %>
				<div class="col-md-2">
				 		<h3 class="text-center latest-5-job">Latest 5 Jobs</h3>

					 		 <ol>

				  		 		<% @gigs.last(5).each do |gig| %>

				   					<li> <%= link_to gig.name, gig %> 	</li>
									<% end %>

				 			 </ol>
					</div>
					<div class="col-md-8">

								<% @gigs.each do |gig| %>
										<div class="all-jobs">
												<h3><%= link_to gig.name, gig %> </h3>
												 <small  class="  ">posted: <%= gig.created_at.strftime("%b %d, %Y") %></small>
									  </div>
								 <% end %>
								 <div class="pull-right">
									<%= paginate @gigs %>

								</div>

				 </div>
					<div class="right-sidebar-all-jobs">
						 <div class="col-md-2">
							 <%= form_tag search_gigs_path, method: :get do |f| %>
							 	<%= text_field_tag :search, nil, placeholder: "Example: Backend developer", class: 'form-control' %>
								<%= submit_tag "Search", class: 'btn btn-primary' %>
							 <% end %>

						 </div>
					</div>
					<% else %>
					<div class="col-md-12 ">
				 		<h3 class=" text-center latest-5-job ">Latest 5 Jobs</h3>

					 		  <div class="text-center ">
					 		  <% if !user_signed_in? %>
						 <%= link_to "Find more awesome jobs, register for free", new_user_registration_path, class: "btn btn-info-morejob " %>
						 <% end %>
					</div>

				  		 		<% @gigs.last(5).each do |gig| %>
				   			<div class="all-jobs ">
				   				 <h3> <%= link_to gig.name, gig %> </h3>
				   				 <h5><b>description:</b> <%= gig.description %></h5>
				   				  <h5><b>Location:</b> <%= gig.location %></h5>
				   				  <h5><b>Budget: $</b><%= gig.budget %>, 00</h5>
				   				   <small  class="  ">posted: <%= gig.created_at.strftime("%b %d, %Y") %></small>
				   			 	</div>
									<% end %>


					</div>

					<% end %>
					 <% if !user_signed_in? %>
					<div class="text-center  e">
						 <%= link_to "Find more awesome jobs, register for free", new_user_registration_path, class: "btn btn-info-morejob  " %>
						 <% end %>
					</div>

			</div>
	</div>

app/views/gigs/new.html.erb
<div class="contents">
	<section id="post">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-md-12">
					<h3 class="sub-heading">Post a Job</h3>
					<div class="content-inner-detail">
					 	<%= form_for @gig do |f| %>
					 			<div class="row">
					 				<div class="col-xs-12 col-md-6">
					 					<div class="form-group">
					 						<%= f.label :name %>
					 						<%= f.text_field :name, class: 'form-control input-lg' %>
					 						<small class="help-block">Name of your Job</small>
					 					</div>
					 				</div>
					 					<div class="col-xs-12 col-md-6">
					 					<div class="form-group">
					 						<%= f.label :budget %>
					 						<%= f.text_field :budget, class: 'form-control input-lg' %>
					 						<small class="help-block">example: $100,00</small>
					 					</div>
					 				</div>
					 			</div>	
					 			<div class="row">
					 			<div class="col-xs-12 col-md-6">
					 					<div class="form-group">
					 						<%= f.label :location %>
					 						<%= f.text_field :location, class: 'form-control input-lg' %>
					 						<small class="help-block">example: Los Angeles, Denver...</small>
					 					</div>
					 				</div>
					 				<div class="col-xs-12 col-md-6">
					 					<div class="form-group">
					 						<%= f.label :description %>
					 						<%= f.text_area :description, class: 'form-control row:10' %>
					 						<small class="help-block">Tell us evrything about your Job request( programmer, front-end, make website responsive...)</small>
					 					</div>
					 				</div> 
					 			</div>
					 			<%= f.submit class: "btn btn-primary input-lg" %>
					 	<% end %>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/gigs/search.html.erb
<div class="search-page">
	<div class="container">
			<div class="col-md-9">
        <h2>Search results</h2>

      </div>
    </div>
  </div>

app/views/gigs/show.html.erb
<div class="show-job-page">
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<h1>Job position: <%= @gig.name %></h1> <%= link_to "Back", root_path, class: "btn btn-info pull-right" %>   <br>
				<h4>Description: <%= @gig.description %></h4> <br>
				<h5>Job location: <%= @gig.location %></h5> <br>
				<h5>Budget: $<%= @gig.budget %> </h5>
			</div>
			<div class="col-xs-12 col-md-4">
				<div class="content-inner-detail">
					<legend>Submit a Proposal</legend>
					<%= form_for :proposal, url: gig_proposals_path(@gig) do |f| %>
					<div class="row">
						<div class="col-xs-12 col-md-12">
								<div class="form-group">
									<%= f.label :bid %>
									<%= f.text_field :bid, rows: 5, class: "form-control input-lg" %>
									<small class="help-block">Amountt of your bid</small>
								</div>
						</div>
						<div class="col-xs-12 col-md-12">
								<div class="form-group">
									<%= f.label :description %>
									<%= f.text_area :description, rows: 5, class: "form-control input-lg" %>
									<small class="help-block">Explain the skills needed for this job.</small>
								</div>
						</div>
					</div>
					<br>
					<%= f.submit "Submit a proposal", class: "btn btn-primary input-lg" %>
					<% end %>
				</div>
			</div>

		</div>

	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
		<div class="container">
				<div class="row">
						<div class="col-md-3">
							<h3>About US</h3>
							<p>Lorem ipsum...</p>
						</div>
						<div class="col-md-3">
							<h3>Get In Touch</h3>
							<p>Lorem ipsum...</p>
						</div>
						<div class="col-md-3">
							<h3>Helpful links</h3>
						<ul>
									<li>Browse all jobs</li>
									<li>Post a Job</li>
									<li>Sign Up</li>
									<li>Sign In</li> 
							</ul>
						</div>
						<div class="col-md-3">
							<h3>Trending Jobs</h3>
							<ul>
									<li>React JS Developer</li>
									<li>Ruby on Rails programmer</li>
									<li>Django Developer</li>
									<li>UX/UI Designer</li>
									<li>Account Manager</li>
							</ul>
						</div>
				</div>
		</div>
</div>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to ('NewJob'), root_path, class: 'navbar-brand' %>
        </div>

        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">


            <% if user_signed_in? %>
              <li><a href="#">Browse all jobs</a></li>
              <%= link_to "Post a Job &raquo;".html_safe, new_gig_path, class: "btn btn-info "%> 
              <%= link_to "Profile",  profile_index_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-warning navbar-btn", method: :delete %>

              <% else %>
              <%=link_to "Sign In", new_user_session_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning navbar-btn" %>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobportal</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>